name: GitHub-Profile-3D-Contrib
on:
  schedule:
    # Runs at 18:00 UTC every day (which is 23:30 IST / 11:30 PM India Standard Time)
    - cron: "0 18 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: '{"dark_mode":true,"color_theme":"rainbow"}' # <--- MODIFIED LINE
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated 3D contribution graph"; then
            git push
          fi
